steps:
  # Step 1: Build Docker image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/be-baretta", "."]
    dir: "notes-backend"  # Ganti jika folder kamu berbeda

  # Step 2: Push Docker image ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/be-baretta"]

  # Step 3: Deploy image ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be",  # Nama service Cloud Run
        "--image",
        "gcr.io/$PROJECT_ID/be-baretta",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--timeout",
        "1000s",
        "--port",
        "8080"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
